# Generated by Django 3.1.2 on 2023-08-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230829_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='scope',
            field=models.ManyToManyField(related_name='scopes', through='articles.Scope', to='articles.Article'),
        ),
    ]
