# Generated by Django 3.1.2 on 2023-08-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20230829_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='scope',
        ),
        migrations.AddField(
            model_name='tag',
            name='scopes',
            field=models.ManyToManyField(related_name='tags', through='articles.Scope', to='articles.Article'),
        ),
    ]
