# Generated by Django 3.1.2 on 2023-08-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20230829_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='scopes',
            field=models.ManyToManyField(related_name='tag', through='articles.Scope', to='articles.Article'),
        ),
    ]
