# Generated by Django 3.1.2 on 2023-08-29 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20230829_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='scopes',
            field=models.ManyToManyField(related_name='temp', through='articles.Scope', to='articles.Article'),
        ),
    ]
