# Generated by Django 3.1.2 on 2023-08-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20230829_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='topic',
            new_name='name',
        ),
    ]
